AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    Microservice:
        Type: String


Conditions:
    IsProdCondition: !Equals [!Ref Stage, "prod"]

Resources:
    GroupsPermissions:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Stage}_${Tenant}_groups_permissions
            AttributeDefinitions:
              - AttributeName: group
                AttributeType: S
            KeySchema:
              - AttributeName: group
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            Tags:
              - Key: Service
                Value: DynamoDB
              - Key: Resource
                Value: Table
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}_groups
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: !If [IsProdCondition, true, false]


Outputs:
    Groups:
        Description: Groups Permissions Table
        Value: !Ref GroupsPermissions
        Export:
            Name: !Sub ${Stage}-${Tenant}-groups-permissions-table
