AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    Microservice:
        Type: String


Conditions:
    IsProdCondition: !Equals [!Ref Stage, "prod"]

Resources:
    UserGroups:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Stage}_${Tenant}_user_groups
            AttributeDefinitions:
              - AttributeName: user
                AttributeType: S
            KeySchema:
              - AttributeName: user
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            Tags:
              - Key: Service
                Value: DynamoDB
              - Key: Resource
                Value: Table
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}_user_groups
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: !If [IsProdCondition, true, false]

    Groups:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Stage}_${Tenant}_groups
            AttributeDefinitions:
              - AttributeName: group
                AttributeType: S
            KeySchema:
              - AttributeName: group
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            Tags:
              - Key: Service
                Value: DynamoDB
              - Key: Resource
                Value: Table
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}_groups
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: !If [IsProdCondition, true, false]

Outputs:
    UserGroups:
        Description: UserGroups
        Value: !Ref UserGroups
        Export:
            Name: !Sub ${Stage}-${Tenant}-user-groups-table

    Groups:
        Description: Groups
        Value: !Ref Groups
        Export:
            Name: !Sub ${Stage}-${Tenant}-groups-table
